FROM node:20

WORKDIR /app

# Copiamos solo package.json y package-lock.json para instalar dependencias primero
COPY package*.json ./
RUN npm install

# Copiamos el resto del proyecto
COPY . .

EXPOSE 3000

# Levantamos el proyecto usando el script correcto
CMD ["npm", "start", "--", "--host", "0.0.0.0"]
