version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass
    networks:
      - appnet

  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    networks:
      - appnet

  publisher:
    build: ./publisher
    container_name: publisher
    depends_on:
      - rabbitmq
      - db
    environment:
      - RABBITMQ_URL=amqp://user:pass@rabbitmq:5672/
      - DATABASE_URL=postgres://appuser:secret@db:5432/appdb?sslmode=disable
    ports:
      - "8080:8080"
    networks:
      - appnet

  consumer:
    build: ./consumer
    depends_on:
      - rabbitmq
      - db
    environment:
      - RABBITMQ_URL=amqp://user:pass@rabbitmq:5672/
      - DATABASE_URL=postgres://appuser:secret@db:5432/appdb?sslmode=disable
    deploy:
      replicas: 3
    networks:
      - appnet

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    # depends_on:
    #   - publisher
    environment:
      - API_URL=http://publisher:8080
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
