services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-golang-example
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass
    networks:
      - appnet

  publisher:
    build: ./publisher
    container_name: publisher
    ports:
      - "8080:8080"
    environment:
      RABBITMQ_URL: "amqp://user:pass@rabbitmq:5672/"
    depends_on:
      - rabbitmq
    networks:
      - appnet

  consumer:
    build: ./consumer
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://user:pass@rabbitmq:5672/
    deploy:
      replicas: 3
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
